/**
* prso_gmaps.js
* 
* The core script to init google maps, set markers, add info windows
* as well as handle any external actions from the #prso-gmaps-actions dom container
* 
* NOTE:: 	All marker place data is passed via localized json object 'prsoGmapPlaces'
*			All map init options are passed via json object 'prsoGmapOptions'
*
* @param	Object	prsoGmapPlaces
* @param	Object	prsoGmapOptions
* @access 	public
* @author	Ben Moody
*/jQuery(document).ready(function(e){function a(){return e("html").hasClass("ie8")?!0:!1}function f(e,t,n,r,i){if(i===!1){e||(e=new google.maps.InfoWindow);e.setContent(t.html);e.open(r,n)}else e=l(e,t,n,r);return e}function l(e,t,n,r){var i;i={content:t.html,disableAutoPan:!1,maxWidth:0,pixelOffset:new google.maps.Size(-140,-30),zIndex:null,boxStyle:{background:null,opacity:null,width:"280px"},boxClass:"infoBox",closeBoxMargin:"10px 2px 2px 2px",closeBoxURL:"http://www.google.com/intl/en_us/mapfiles/close.gif",infoBoxClearance:new google.maps.Size(1,1),isHidden:!1,pane:"floatPane",enableEventPropagation:!1,alignBottom:!0};e||(e=new InfoBox(i));e.setContent(t.html);e.open(r,n);return e}function c(e,t){var n,r,i,s,o;n=e+1;r=new google.maps.MarkerImage(prsoGmapOptions.markerImages+"/mouseout/number_"+n+".png");i=new google.maps.MarkerImage(prsoGmapOptions.markerImages+"/mouseover/number_"+n+".png");s=new google.maps.MarkerImage(prsoGmapOptions.markerImages+"/mouseout/number_"+n+".png");o=new google.maps.MarkerImage(prsoGmapOptions.markerImages+"/mouseover/number_"+n+".png");t.setIcon(r);google.maps.event.addListener(t,"mouseout",function(){this.setIcon(r)});google.maps.event.addListener(t,"mouseover",function(){this.setIcon(i)});google.maps.event.addListener(t,"mousedown",function(){this.setIcon(s)});google.maps.event.addListener(t,"mouseup",function(){this.setIcon(o)})}function h(e){google.maps.event.trigger(i[e],"click")}var t,n=prsoGmapOptions.canvasID,r=prsoGmapPlaces,i=[],t,s={zoom:Number(prsoGmapOptions.zoom),mapTypeControl:!1,center:new google.maps.LatLng(prsoGmapOptions.center.lat,prsoGmapOptions.center.lng),mapTypeId:google.maps.MapTypeId.ROADMAP},o=new google.maps.Map(document.getElementById(n),s),u=new google.maps.LatLngBounds;e.each(r,function(e,n){var r=new google.maps.LatLng(n.lat,n.lng),s=new google.maps.Marker({position:r,map:o,title:n.title});i.push(s);(function(e,r){c(e,r);google.maps.event.addListener(r,"click",function(){var e=!0;a()&&(e=!1);t=f(t,n,r,o,e)})})(e,s);u.extend(r)});o.fitBounds(u);e("#prso-gmaps-actions a").click(function(t){t.preventDefault();var n;n=e(this).attr("rel");h(n);e("#prso-gmaps-actions li").removeClass("active");e(this).closest("li").addClass("active")})});